### ISSUE TITLE
@rec concordance issue between doc and usage

### ISSUE THREAD

**Issue by mariusmjp** [bankofcanada/TimeSeriesEcon.jl#10]
Hi,

When I read the doc we should be use @rec(eqn,rng) but when I go inside the code this is inverse the first argument is rng and second eqn.
![@rec_no_concordance](https://user-images.githubusercontent.com/22647406/93518369-b6c38200-f8fa-11ea-859b-fc66548a922f.png)

**Comment by kunov** [comment]
https://github.com/bankofcanada/TimeSeriesEcon.jl/commit/15e58220191d269823367a2c5ec1585d173611d6

thanks Jose, the docstring changed in the commit above.
