### ISSUE TITLE
compare: bound error

### ISSUE THREAD

**Issue by Nic2020** [bankofcanada/TimeSeriesEcon.jl#22]
The following code generates a bound error.

```
d1 = Workspace()
d1.a = TSeries(2000Q1,randn(10))
d1.b = TSeries(2000Q1,randn(10))
d2 = deepcopy(d1)
d2.a = d1.a[2001Q1:2001Q1]
d1.a = TSeries(1960Q1,randn(10))
compare(d1,d2; atol = 1e-8)
```
![bounderror](https://user-images.githubusercontent.com/30166151/191806752-db361250-3ad5-4eab-adba-9ff63055a423.png)

**Comment by bbejanov** [comment]
Fix is in the dev branch, will be merged with PR #21
