### ISSUE TITLE
Issue when you use 1-TSeries

### ISSUE THREAD

**Issue by mariusmjp** [bankofcanada/TimeSeriesEcon.jl#6]
Hi

Maybe you already aware of that but just in case I found an issue with TimeSeriesEcon.

**1-TSeries(object)** return an issue but **-TSeries(object) + 1** seems working.
![issue_with_minus](https://user-images.githubusercontent.com/22647406/90137983-57df7b80-dd44-11ea-9587-ce24098fd1fd.png)

**Comment by kunov** [comment]
https://github.com/bankofcanada/TimeSeriesEcon.jl/commit/521ae3992b665c46ce89d925f2274da7f14311c4

This issues is addressed. Currently two methods to do this:

 - `1 - ts`: to mimic IRIS
 - `1 .- ts`: using Julia broadcasting capabilities
